"""Tests for mattstack rules sync (harness-agnostic adapters)."""

from __future__ import annotations

from pathlib import Path

import pytest
import typer

from mattstack.commands.rules import (
    HARNESS_ADAPTERS,
    collect_canonical,
    render_adapter,
    sync_harness_rules,
)


def test_collect_canonical_concatenates_sorted(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".context").mkdir()
    (tmp_path / ".omp" / "RULES.md").write_text("# Rules\n", encoding="utf-8")
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / ".context" / "CONTEXT.md").write_text("# Context\n", encoding="utf-8")

    canonical = collect_canonical(tmp_path)

    assert "AGENTS.md" in canonical
    assert "RULES.md" in canonical
    assert "CONTEXT.md" in canonical
    assert canonical.index("AGENTS.md") < canonical.index("RULES.md")
    assert canonical.index("RULES.md") < canonical.index("CONTEXT.md")


def test_collect_canonical_ignores_non_md(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "notes.txt").write_text("ignored\n", encoding="utf-8")

    assert collect_canonical(tmp_path) == ""


def test_render_adapter_adds_header() -> None:
    out = render_adapter("body")

    assert "Generated by `mattstack rules sync`" in out
    assert "body" in out


def test_sync_writes_all_adapters(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path)

    assert len(written) == len(HARNESS_ADAPTERS)
    for rel in HARNESS_ADAPTERS.values():
        target = tmp_path / rel
        assert target.exists()
        assert "# Agents" in target.read_text(encoding="utf-8")


def test_sync_skips_existing_without_force(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / ".claude").mkdir(parents=True)
    (tmp_path / ".claude" / "CLAUDE.md").write_text("hand-edited\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path)

    assert (tmp_path / ".claude" / "CLAUDE.md").read_text(encoding="utf-8") == "hand-edited\n"
    assert len(written) == len(HARNESS_ADAPTERS) - 1


def test_sync_force_overwrites(tmp_path: Path) -> None:
    (tmp_path / ".omp").mkdir()
    (tmp_path / ".omp" / "AGENTS.md").write_text("# Agents\n", encoding="utf-8")
    (tmp_path / ".claude").mkdir(parents=True)
    (tmp_path / ".claude" / "CLAUDE.md").write_text("hand-edited\n", encoding="utf-8")

    written = sync_harness_rules(tmp_path, force=True)

    assert "# Agents" in (tmp_path / ".claude" / "CLAUDE.md").read_text(encoding="utf-8")
    assert len(written) == len(HARNESS_ADAPTERS)


def test_sync_errors_without_canonical(tmp_path: Path) -> None:
    with pytest.raises(typer.Exit) as exc:
        sync_harness_rules(tmp_path)

    assert exc.value.exit_code == 1
